language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"

matrix:
  include:
    - python: 3.7
      dist: bionic
      env: DIST="bionic"
      
    - python: 3.8
      dist: bionic
      env: DIST="bionic"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y iputils-ping

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
 - pip install --upgrade .
 
script:  
 - cd tests
 - nosetests -v nocoverage
 - nosetests -v --with-coverage --cover-package=easyprocess coverage
 
after_success:
 - coveralls
