language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y iputils-ping

install:
 - pip install coveralls
 - pip install -r requirements-test.txt
 - pip install --upgrade .
 
script:  
 - cd tests
 - nosetests -v nocoverage
 - nosetests -v --with-coverage --cover-package=easyprocess coverage
 
after_success:
 - coveralls
